/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c StagingNotifierAdaptor -a staging_adaptor.h:staging_adaptor.cpp org.kde.StagingNotifier.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef STAGING_ADAPTOR_H
#define STAGING_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.kde.StagingNotifier
 */
class StagingNotifierAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.StagingNotifier")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.StagingNotifier\">\n"
"    <signal name=\"listChanged\"/>\n"
"    <method name=\"watchDir\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"path\"/>\n"
"    </method>\n"
"    <method name=\"removeDir\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"path\"/>\n"
"    </method>\n"
"    <method name=\"sendList\">\n"
"      <arg direction=\"out\" type=\"as\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    StagingNotifierAdaptor(QObject *parent);
    virtual ~StagingNotifierAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void removeDir(const QString &path);
    QStringList sendList();
    void watchDir(const QString &path);
Q_SIGNALS: // SIGNALS
    void listChanged();
};

#endif
