/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c StagingNotifierAdaptor -a staging_adaptor.h:staging_adaptor.cpp org.kde.StagingNotifier.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "staging_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class StagingNotifierAdaptor
 */

StagingNotifierAdaptor::StagingNotifierAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

StagingNotifierAdaptor::~StagingNotifierAdaptor()
{
    // destructor
}

void StagingNotifierAdaptor::removeDir(const QString &path)
{
    // handle method call org.kde.StagingNotifier.removeDir
    QMetaObject::invokeMethod(parent(), "removeDir", Q_ARG(QString, path));
}

void StagingNotifierAdaptor::sendList()
{
    // handle method call org.kde.StagingNotifier.sendList
    QMetaObject::invokeMethod(parent(), "sendList");
}

void StagingNotifierAdaptor::watchDir(const QString &path)
{
    // handle method call org.kde.StagingNotifier.watchDir
    QMetaObject::invokeMethod(parent(), "watchDir", Q_ARG(QString, path));
}

